Criando endpoint de uma rota e validando mais de uma rota com destino…
MILTONRUBRO/api-site-viagem pull request #4
Opened 2020-04-07 20:12 UTC by MILTONRUBRO

… e origem iguais

2020-04-07 20:14 UTC, MILTONRUBRO reviewed
não sei se essa é a melhor forma para validar duas rotas com possiveis destino e origem iguais, mas quebrei um pouco a cabeça para monta-la

2020-04-08 10:31 UTC, asouza requested changes
Adicionei mais uma restrição lá: a rota não pode ter o mesmo aeroporto de origem e destino

2020-04-08 10:31 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/controllers/RotaController.java
> +	@InitBinder("rotaForm")
aqui, se quiser, pode até tirar.

2020-04-08 10:31 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/Rota.java
> +	private @NotNull @Positive int duracao;
Opa, aqui, como você declarou o tipo como int(primitivo) a própria linguagem garante que ele nunca vai ser nulo. Inclusive, se você olhar a tabela gerada, vai ver que o valor default é zero :). Se quiser deixar int, talvez seja bom dizer que o mínimo é 1(uma hora).

2020-04-08 10:31 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/Rota.java
> +	private @NotNull @Positive int duracao;
Claro que pode colocar integer também... aí usa o NotNull e o mesmo mínimo.

2020-04-08 10:31 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/Rota.java
> +	public boolean equals(Object obj) {
Opa, o equals é um método de negócio. Neste caso, pode considerar que o aeroporto de origem + destino é o que define duas rotas iguais, para o contexto deste projeto claro :).

2020-04-08 10:31 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/Rota.java
> +		if (id == null) {
Lembra que o id não é critério de comparação, já que ele não é uma informação natural do objeto. Uma linha boa de seguir é: se o valor não é definido dentro do código do construtor não faz muito sentido entrar no equals, já que não é essencial.

2020-04-08 10:31 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/RotaForm.java
> +		if (nome == null || nome.isEmpty()) {
Opa, aqui a minha sugestão é você colocar esse comportamento para dentro de uma outra possibilidade de construtor da classe rota :). Testa e vê o que você acha :).

2020-04-08 10:31 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/validator/AeroportoOrigemDestinoRotaValidator.java
> +        boolean found = rotas.stream()
Como essa é uma validação verifica literalmente os dados que estão gravados, você pode bolar uma query que tenta achar uma rota exatamente com este aeroporto de origem e de destino.

2020-04-09 09:39 UTC, asouza requested changes

2020-04-09 09:39 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/RotaForm.java
>  		if (nome == null || nome.isEmpty()) {
Aqiu você pode usar a classe do Spring StringUtils.hasText()

2020-04-09 09:39 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/RotaForm.java
> +		if(idAeroportoOrigem ==  idAeroportoDestino || possivelRota.isPresent()) {
Quem chama esse código é o seu controller e você só recebe como parâmetro os repositories, a operação é toda sobre o estado do próprio objeto. 

Neste ponto, você pode até se defender fazendo uma verificação de estado de ids iguais entre a origem e o destino e soltar um IlegalStateException. Neste ponto é bug se os ids forem iguais, este método não deveria ser chamado nessa condição, alguém deveria ter validado. Não precisamos de uma nova exception :), também não precisamos mapear status http aqui de dentro. 

Sobre a possível rota presente é uma super defesa extra, mas perceba que é uma lógica bem atrelado ao sistema como um todo e não entre atributos deste mesmo objeto. Acho que ela poderia residir no validator normal mesmo mesmo.

2020-04-09 09:39 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/RotaForm.java
> +		if(idAeroportoOrigem ==  idAeroportoDestino || possivelRota.isPresent()) {
Eu mandei um audio sobre isso ontem no grupo. Se o método é chamado diretamente pelo seu código, o estado de tudo deveria ser válido, então você se defende soltando exception que indicam bugs. Agora se o método é chamado em função de uma requisição externa, que é o acontece ali na rota do seu controller, aí você assume que os dados podem estar inválidos e devolve uma resposta bonita explicando o problema.

2020-04-09 09:39 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/RotaForm.java
> +		if(idAeroportoOrigem ==  idAeroportoDestino || possivelRota.isPresent()) {
Ah, completando. Como o cliente pode escolher a origem e o destino iguais, você pode criar um validador customizado para tratar do possível problema.

2020-04-11 00:07 UTC, asouza requested changes
Já está bem bom! Só um detalhezinho

2020-04-11 00:07 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/model/Rota.java
> +	public int hashCode() {
faltou regerar o hashcode em função do equals

2020-04-11 00:07 UTC, asouza commented on src/main/java/br/com/mosdev/apisiteviagem/validator/OrigemDestinoIguaisRotaValidator.java
> +		if(form.getIdAeroportoOrigem().equals(form.getIdAeroportoDestino())){
Você compara o valor de dois estados que residem dentro da mesma classe. Que tal criar o comportamento dentro da classe RotaForm e só chamar o método daqui?

2020-04-11 22:55 UTC, asouza approved these changes
Gooo!

2020-04-11 22:58 UTC, merged